#!/bin/sh

setbg
picom --config ~/.config/picom/dwm.conf &
syncthing --no-browser &
/usr/lib/kdeconnectd &

xrdb ~/.config/x11/xresources & xrdbpid=$!

autostart="steam discord mpd spotify-launcher qbittorrent dunst unclutter pipewire"

for program in $autostart; do
    pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

[ -n "$xrdbpid" ] && wait "$xrdbpid"

# Activate dbus variables
dbus-update-activation-environment --all
ssh-agent dwm
pgrep dwm && dwmblocks &
