#!/bin/sh

dwmblocks &
setbg
picom --config ~/.config/picom/dwm.conf &
xrdb ~/.config/x11/xresources & xrdbpid=$!

autostart=(
    "/usr/lib/kdeconnectd"
    "steam"
    "vesktop"
    "spotify-launcher"
    "qbittorrent"
    "dunst"
    "unclutter"
    "pipewire"
)

for program in "${autostart[@]}"; do
    cmd=$(echo "$program" | awk '{print $1}')
    pidof -sx "$cmd" || $program &
done >/dev/null 2>&1

[ -n "$xrdbpid" ] && wait "$xrdbpid"

dbus-update-activation-environment --all
exec ssh-agent dwm
