#!/bin/sh
# Xsetup - run as root before the login dialog appears
xrandr --dpi 96
xrandr --output DisplayPort-1 --mode 2560x1440 -r 144 --output HDMI-A-0 --mode 2560x1440 -r 75 --left-of DisplayPort-1
