# written by systemd-localed(8), read by systemd-localed and xorg. it's
# probably wise not to edit this file manually. use localectl(1) to
# update this file.
section "inputclass"
        identifier "system-keyboard"
        matchiskeyboard "on"
        option "xkblayout" "us,az"
        option "xkbmodel" "pc104"
        option "xkboptions" "grp:alt_shift_toggle"
endsection
