--lang=en-US
--service-sandbox-type=none
--use-angle=gl
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecoder,AcceleratedVideoEncoder,PdfUseShowSaveFilePicker
--disable-features=HardwareMediaKeyHandling,LocalNetworkAccessChecks,MediaSessionService,ScreenAIOCREnabled,SpareRendererForSitePerProcess,TraceSiteInstanceGetProcessCreation,WinRetrieveSuggestionsOnlyOnDemand
--variations-seed-version
--ignore-gpu-blocklist
