#!/bin/bash

# Start a tmux session when bash starts
if [ -x "$(command -v tmux)" ] && [ -n "${DISPLAY}" ] && [ -z "${TMUX}" ]; then
    # shellcheck disable=SC2046
    parent=$(ps -o comm= -p $(ps -o ppid= -p $$))
    if [ "$parent" = "st" ]; then
        last_session=$(tmux ls 2>/dev/null | awk -F: '{print $1}' | tail -n 1)
        if [ -z "$last_session" ]; then
            session_name=0
        else
            session_name=$((last_session + 1))
        fi
        exec tmux new-session -s "$session_name" >/dev/null 2>&1
    fi
fi
