#!/bin/bash

# Append "$1" to $PATH when not already in.
append_path() {
    case ":$PATH:" in
    *:"$1":*) ;;
    *)
        PATH="${PATH:+$PATH:}$1"
        ;;
    esac
}

# Add user paths
append_path "$XDG_DATA_HOME/cargo/bin"
append_path "$XDG_DATA_HOME/go/bin"
append_path "$XDG_DATA_HOME/npm/bin"

# Export updated PATH
export PATH

# Unload our profile API functions
unset -f append_path
