#!/bin/bash

# XDG_CACHE_HOME
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export NUGET_PACKAGES="$XDG_CACHE_HOME/NuGetPackages"

# XDG_CONFIG_HOME
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export GLOW_STYLE="$XDG_CONFIG_HOME/glow/kuroneko.json"
export GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/ripgreprc"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"

# XDG_DATA_HOME
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
export AZURE_CONFIG_DIR="$XDG_DATA_HOME/azure"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GOPATH="$XDG_DATA_HOME/go"
export NLTK_DATA="$XDG_DATA_HOME/nltk_data"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"

# XDG_STATE_HOME
export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
