#!/bin/bash

source "$XDG_CACHE_HOME/wal/colors.sh"

if [[ -x "$(which zathura)" ]]; then
    zathuraconf="$XDG_CONFIG_HOME/zathura/zathurarc"
    zathura_template="$XDG_CACHE_HOME/wal/zathurarc"
    mv -n "$zathuraconf" "$zathuraconf.bak"
    cp -f "$zathura_template" "$zathuraconf"
    sed -i 's/#background/'"$background"'/g' "$zathuraconf"
    sed -i 's/#foreground/'"$foreground"'/g' "$zathuraconf"
    sed -i 's/#color3/'"$color3"'/g' "$zathuraconf"
    sed -i 's/#color4/'"$color4"'/g' "$zathuraconf"
fi

if [[ -x "$(which dunst)" ]]; then
    dunstconf="$XDG_CONFIG_HOME/dunst/dunstrc"
    dunst_template="$XDG_CACHE_HOME/wal/dunstrc"
    mv -n "$dunstconf" "$dunstconf.bak"
    cp -f "$dunst_template" "$dunstconf"
    sed -i 's/#color0/'"$color0"'/g' "$dunstconf"
    sed -i 's/#color1/'"$color1"'/g' "$dunstconf"
    sed -i 's/#color4/'"$color4"'/g' "$dunstconf"
    sed -i 's/#color8/'"$color8"'/g' "$dunstconf"
    sed -i 's/#color11/'"$color11"'/g' "$dunstconf"
    sed -i 's/#color15/'"$color15"'/g' "$dunstconf"
fi

if [[ -x "$(which pywalfox)" ]]; then
    pywalfox update
fi

if [[ -x "$(which pywal-discord)" ]]; then
    pywal-discord
fi

if [[ -x "$(which 4chan-pywal.sh)" ]]; then
    4chan-pywal.sh
fi

xresources="$XDG_CONFIG_HOME/x11/xresources"

cp -f "$XDG_CACHE_HOME/wal/colors.Xresources" $xresources

cat <<EOF >>$xresources

Xcursor.size: 24
EOF

xrdb $xresources

xcolor4=$(grep -E '^\*.color4:' $xresources | cut -d':' -f2 | tr -d ' ')
sed -i "s/set -g @tmux_power_theme '[^']*'/set -g @tmux_power_theme '$xcolor4'/" $XDG_CONFIG_HOME/tmux/tmux.conf

get_xres_rgb() {
    hex=$(xrdb -query | grep "$1" | awk '{print $2}' | cut -d# -f2)
    printf "%d,%d,%d\n" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

[[ -d "$HOME/.local/share/color-schemes" ]] || mkdir -pv "$HOME/.local/share/color-schemes"

output="$(
    cat <<THEME
[ColorEffects:Disabled]
Color=$(get_xres_rgb color9:)

[ColorEffects:Inactive]
Color=$(get_xres_rgb color9:)

[Colors:Button]
BackgroundNormal=$(get_xres_rgb color8:)
ForegroundNormal=$(get_xres_rgb background:)

[Colors:Complementary]

[Colors:Selection]
BackgroundAlternate=
BackgroundNormal=$(get_xres_rgb color2:)
DecorationFocus=
DecorationHover=
ForegroundActive=
ForegroundInactive=
ForegroundLink=
ForegroundNegative=
ForegroundNeutral=
ForegroundNormal=$(get_xres_rgb foreground:)
ForegroundPositive=
ForegroundVisited=

[Colors:Tooltip]
BackgroundAlternate=
BackgroundNormal=$(get_xres_rgb color2:)
DecorationFocus=
DecorationHover=
ForegroundActive=
ForegroundInactive=
ForegroundLink=
ForegroundNegative=
ForegroundNeutral=
ForegroundNormal=$(get_xres_rgb foreground:)
ForegroundPositive=
ForegroundVisited=

[Colors:View]
# BackgroundAlternate=
BackgroundNormal=$(get_xres_rgb color0:)
# DecorationFocus=
# DecorationHover=
# ForegroundActive=
# ForegroundInactive=
# ForegroundLink=
# ForegroundNegative=
# ForegroundNeutral=
ForegroundNormal=$(get_xres_rgb foreground:)
# ForegroundPositive=
# ForegroundVisited=

[Colors:Window]
# BackgroundAlternate=
BackgroundNormal=$(get_xres_rgb color0:)
# DecorationFocus=
# DecorationHover=
# ForegroundActive=
# ForegroundInactive=
# ForegroundLink=
# ForegroundNegative=
# ForegroundNeutral=
ForegroundNormal=$(get_xres_rgb foreground:)
# ForegroundPositive=
# ForegroundVisited=

[General]
ColorScheme=pywal
Name=pywal
shadeSortColumn=true

[KDE]
contrast=0

[WM]
activeBackground=$(get_xres_rgb background:)
activeForeground=$(get_xres_rgb foreground:)
inactiveBackground=$(get_xres_rgb background:)
inactiveForeground=$(get_xres_rgb color15:)
THEME
)"
printf '%s' "$output" >"$HOME/.local/share/color-schemes/pywal.colors"

sed -i 's/bg:0/bg:-1/g' colors.sh
